#!/usr/bin/env python3
"""Rebuild and independently validate the weld-test STEP deliverables.

The build path is DXF -> ezdxf entity import -> CadQuery/OpenCascade B-Rep
operations -> STEP AP214. No STEP entity text is generated by this script.

Run ``build`` and ``validate`` as separate processes. This makes process exit
the explicit close boundary before the validation process reopens every STEP.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import json
import math
import re
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

import cadquery as cq
import ezdxf
import OCP
from cadquery import importers
from OCP.IFSelect import IFSelect_ReturnStatus
from OCP.Interface import Interface_Static


ROOT = Path(__file__).resolve().parents[2]
DXF_DIR = ROOT / "laser" / "dxf-parts"
PART_STEP_DIR = ROOT / "cad" / "parts"
ASSEMBLY_STEP_DIR = ROOT / "cad" / "assembly"
NATIVE_PART_DIR = ROOT / "cad" / "native" / "parts"
NATIVE_ASSEMBLY_DIR = ROOT / "cad" / "native" / "assembly"
METADATA_PATH = ROOT / "cad" / "native" / "build-metadata.json"
REPORT_PATH = ROOT / "documents" / "release" / "STEP_VALIDATION_REPORT.md"
VALIDATION_JSON_PATH = ROOT / "documents" / "release" / "step-validation.json"

INCH_TO_MM = 25.4
THICKNESS_IN = 0.135
THICKNESS_MM = THICKNESS_IN * INCH_TO_MM
STEP_SCHEMA = "AP214IS"
ZERO_VOLUME_MM3 = 1.0e-6
DIMENSION_TOLERANCE_MM = 1.0e-5
VOLUME_REL_TOLERANCE = 1.0e-7

PART_FILENAMES = (
    "WT-001_BASE",
    "WT-002_SPINE",
    "WT-003_CROSS",
    "WT-004_VERTICAL",
    "WT-005_CORNER_A",
    "WT-006_CORNER_B",
    "WT-007_LAP_LOWER",
    "WT-008_LAP_UPPER",
    "WT-009_BUTT_A",
    "WT-010_BUTT_B",
    "WT-011_GAP_GAUGE",
    "WT-012_SLOT_COUPON",
)
ASSEMBLY_COMPONENTS = PART_FILENAMES[:10]
ASSEMBLY_FILENAME = "LXD_10GA_MIG_WELD_TEST_ASSEMBLY"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _point_key(point: Any) -> tuple[float, float, float]:
    return tuple(round(float(value), 12) for value in point)


def write_deduplicated_import_copy(source: Path, destination: Path) -> int:
    """Write a temporary DXF with exact duplicate CUT lines removed.

    The released WT-006 profile contains one identical four-line tab loop
    twice. Removing only exact, direction-independent duplicates does not
    alter the profile region or any coordinate.
    """

    document = ezdxf.readfile(source)
    modelspace = document.modelspace()
    seen: set[tuple[tuple[float, float, float], tuple[float, float, float]]] = set()
    removed = 0

    for entity in list(modelspace):
        if entity.dxftype() != "LINE" or entity.dxf.layer != "CUT":
            continue
        key = tuple(
            sorted((_point_key(entity.dxf.start), _point_key(entity.dxf.end)))
        )
        if key in seen:
            modelspace.delete_entity(entity)
            removed += 1
        else:
            seen.add(key)

    document.saveas(destination)
    return removed


def _wire_prism(wire: cq.Wire) -> cq.Solid:
    if not wire.IsClosed():
        raise ValueError("DXF CUT contour is not closed")
    scaled = wire.scale(INCH_TO_MM)
    return cq.Solid.extrudeLinear(
        scaled,
        [],
        cq.Vector(0.0, 0.0, THICKNESS_MM),
    )


def import_dxf_solid(source: Path, scratch: Path) -> tuple[cq.Shape, dict[str, Any]]:
    """Import one DXF and construct one exact prismatic B-Rep solid."""

    cleaned = scratch / f"{source.stem}-deduplicated.dxf"
    duplicate_count = write_deduplicated_import_copy(source, cleaned)
    imported_faces = [
        value
        for value in importers.importDXF(str(cleaned), include=["CUT"]).vals()
        if value.ShapeType() == "Face"
    ]
    if not imported_faces:
        raise ValueError(f"{source.name}: no closed CUT profiles were imported")

    regions: list[cq.Shape] = []
    contour_count = 0
    for imported_face in imported_faces:
        wires = imported_face.Wires()
        if not wires:
            raise ValueError(f"{source.name}: imported face contains no wire")

        # CadQuery's DXF importer identifies one exterior wire followed by its
        # interior contours. Extrude the exterior alone, then cut each interior
        # contour sequentially. This permits exact intersecting cut contours in
        # WT-001 without asking OpenCascade to create an invalid planar face.
        region: cq.Shape = _wire_prism(wires[0])
        contour_count += 1
        for inner_wire in wires[1:]:
            region = region.cut(_wire_prism(inner_wire))
            contour_count += 1
        regions.append(region)

    solid: cq.Shape = regions[0]
    for region in regions[1:]:
        solid = solid.fuse(region)
    solid = solid.clean()

    solids = solid.Solids()
    if len(solids) != 1:
        raise ValueError(
            f"{source.name}: expected one solid after import, found {len(solids)}"
        )
    if not solid.isValid():
        raise ValueError(f"{source.name}: OpenCascade reports invalid topology")
    if solid.Volume() <= ZERO_VOLUME_MM3:
        raise ValueError(f"{source.name}: imported solid has zero volume")

    box = solid.BoundingBox()
    return solid, {
        "source": source.relative_to(ROOT).as_posix(),
        "source_sha256": sha256(source),
        "exact_duplicate_cut_lines_removed_in_memory": duplicate_count,
        "closed_cut_contours": contour_count,
        "solid_count": len(solids),
        "volume_mm3": solid.Volume(),
        "bounding_mm": [box.xlen, box.ylen, box.zlen],
    }


def _configure_step_ap214() -> None:
    Interface_Static.SetCVal_s("write.step.schema", STEP_SCHEMA)
    Interface_Static.SetCVal_s("xstep.cascade.unit", "MM")
    Interface_Static.SetCVal_s("write.step.unit", "MM")


def export_part_step(shape: cq.Shape, destination: Path) -> None:
    _configure_step_ap214()
    status = shape.exportStep(
        str(destination),
        unit="MM",
        outputUnit="MM",
        write_pcurves=True,
        precision_mode=0,
    )
    if status != IFSelect_ReturnStatus.IFSelect_RetDone:
        raise RuntimeError(f"STEP export failed for {destination}: {status}")


def vertical_xz(
    shape: cq.Shape,
    *,
    x_origin_in: float,
    y_center_in: float,
    body_bottom_in: float = THICKNESS_IN,
) -> cq.Shape:
    """Place a profile's X/Y plane along assembly X/Z."""

    rotated = shape.rotate((0, 0, 0), (1, 0, 0), 90)
    return rotated.translate(
        (
            x_origin_in * INCH_TO_MM,
            y_center_in * INCH_TO_MM + THICKNESS_MM / 2.0,
            body_bottom_in * INCH_TO_MM,
        )
    )


def vertical_yz(
    shape: cq.Shape,
    *,
    x_center_in: float,
    y_origin_in: float,
    body_bottom_in: float = THICKNESS_IN,
) -> cq.Shape:
    """Place a profile's X/Y plane along assembly Y/Z."""

    rotated = shape.rotate((0, 0, 0), (1, 0, 0), 90)
    rotated = rotated.rotate((0, 0, 0), (0, 0, 1), 90)
    return rotated.translate(
        (
            x_center_in * INCH_TO_MM - THICKNESS_MM / 2.0,
            y_origin_in * INCH_TO_MM,
            body_bottom_in * INCH_TO_MM,
        )
    )


def flat(
    shape: cq.Shape,
    *,
    x_origin_in: float,
    y_origin_in: float,
    z_origin_in: float = 0.0,
) -> cq.Shape:
    return shape.translate(
        (
            x_origin_in * INCH_TO_MM,
            y_origin_in * INCH_TO_MM,
            z_origin_in * INCH_TO_MM,
        )
    )


def place_assembly_components(parts: dict[str, cq.Shape]) -> dict[str, cq.Shape]:
    """Place the ten intended components from the controlled Rev A sequence."""

    return {
        "WT-001_BASE": flat(
            parts["WT-001_BASE"], x_origin_in=0.0, y_origin_in=0.0
        ),
        "WT-002_SPINE": vertical_xz(
            parts["WT-002_SPINE"], x_origin_in=1.0, y_center_in=6.0
        ),
        "WT-003_CROSS": vertical_yz(
            parts["WT-003_CROSS"], x_center_in=6.0, y_origin_in=1.0
        ),
        "WT-004_VERTICAL": vertical_xz(
            parts["WT-004_VERTICAL"], x_origin_in=1.5, y_center_in=2.0
        ),
        "WT-005_CORNER_A": vertical_xz(
            parts["WT-005_CORNER_A"], x_origin_in=7.0, y_center_in=2.0
        ),
        "WT-006_CORNER_B": vertical_yz(
            parts["WT-006_CORNER_B"], x_center_in=10.0, y_origin_in=2.0
        ),
        "WT-007_LAP_LOWER": vertical_xz(
            parts["WT-007_LAP_LOWER"], x_origin_in=1.5, y_center_in=10.0
        ),
        # A one-inch X overlap and one material-thickness Y offset create the
        # documented lap joint while keeping the two solids distinct.
        "WT-008_LAP_UPPER": vertical_xz(
            parts["WT-008_LAP_UPPER"],
            x_origin_in=4.5,
            y_center_in=10.0 + THICKNESS_IN,
        ),
        # The controlled sequence places the butt coupons on a separate test
        # area. Their long edges face each other across the specified root gap.
        "WT-009_BUTT_A": flat(
            parts["WT-009_BUTT_A"], x_origin_in=13.0, y_origin_in=0.0
        ),
        "WT-010_BUTT_B": flat(
            parts["WT-010_BUTT_B"],
            x_origin_in=13.0,
            y_origin_in=2.0 + 0.045,
        ),
    }


def make_assembly(placed: dict[str, cq.Shape]) -> cq.Assembly:
    assembly = cq.Assembly(name=ASSEMBLY_FILENAME)
    colors = (
        cq.Color(0.78, 0.82, 0.86),
        cq.Color(0.86, 0.55, 0.31),
        cq.Color(0.38, 0.60, 0.82),
        cq.Color(0.49, 0.70, 0.44),
        cq.Color(0.75, 0.55, 0.75),
        cq.Color(0.90, 0.72, 0.35),
        cq.Color(0.38, 0.74, 0.70),
        cq.Color(0.74, 0.43, 0.43),
        cq.Color(0.55, 0.55, 0.60),
        cq.Color(0.65, 0.65, 0.70),
    )
    for name, color in zip(ASSEMBLY_COMPONENTS, colors):
        assembly.add(placed[name], name=name, color=color)
    return assembly


def shape_summary(shape: cq.Shape) -> dict[str, Any]:
    box = shape.BoundingBox()
    return {
        "solid_count": len(shape.Solids()),
        "face_count": len(shape.Faces()),
        "volume_mm3": shape.Volume(),
        "bounding_mm": [box.xlen, box.ylen, box.zlen],
        "valid": shape.isValid(),
    }


def build() -> None:
    for directory in (
        PART_STEP_DIR,
        ASSEMBLY_STEP_DIR,
        NATIVE_PART_DIR,
        NATIVE_ASSEMBLY_DIR,
        METADATA_PATH.parent,
    ):
        directory.mkdir(parents=True, exist_ok=True)

    parts: dict[str, cq.Shape] = {}
    part_metadata: dict[str, Any] = {}
    with tempfile.TemporaryDirectory(prefix="weld-test-dxf-import-") as temp:
        scratch = Path(temp)
        for name in PART_FILENAMES:
            source = DXF_DIR / f"{name}.dxf"
            if not source.is_file():
                raise FileNotFoundError(f"Authoritative DXF is missing: {source}")
            shape, metadata = import_dxf_solid(source, scratch)
            parts[name] = shape
            part_metadata[name] = metadata

            export_part_step(shape, PART_STEP_DIR / f"{name}.step")
            shape.exportBrep(str(NATIVE_PART_DIR / f"{name}.brep"))

    placed = place_assembly_components(parts)
    assembly = make_assembly(placed)
    assembly_step = ASSEMBLY_STEP_DIR / f"{ASSEMBLY_FILENAME}.step"
    _configure_step_ap214()
    assembly.export(
        str(assembly_step),
        exportType="STEP",
        mode="default",
        unit="MM",
        outputUnit="MM",
        write_pcurves=True,
        precision_mode=0,
    )
    assembly.export(
        str(NATIVE_ASSEMBLY_DIR / f"{ASSEMBLY_FILENAME}.xbf"),
        exportType="XBF",
    )
    assembly.toCompound().exportBrep(
        str(NATIVE_ASSEMBLY_DIR / f"{ASSEMBLY_FILENAME}.brep")
    )

    metadata = {
        "cad_software": f"CadQuery {cq.__version__}",
        "cad_kernel": f"OpenCascade {OCP.__version__}",
        "dxf_reader": f"ezdxf {ezdxf.__version__}",
        "step_protocol_requested": "AP214",
        "step_schema_setting": STEP_SCHEMA,
        "model_units": "millimeter",
        "source_profile_units": "inch",
        "thickness_in": THICKNESS_IN,
        "thickness_mm": THICKNESS_MM,
        "parts": part_metadata,
        "assembly": {
            "filename": assembly_step.relative_to(ROOT).as_posix(),
            "intended_components": list(ASSEMBLY_COMPONENTS),
            "component_count": len(ASSEMBLY_COMPONENTS),
            "placed_component_summaries": {
                name: shape_summary(placed[name]) for name in ASSEMBLY_COMPONENTS
            },
            "placement_basis": [
                "Controlled Rev A assembly sequence",
                "WT-001 etched station labels",
                "1.00 inch documented lap overlap",
                "0.045 inch documented butt root opening",
            ],
        },
        "warnings": [
            (
                "The controlled package provides a concept view and assembly "
                "sequence but no dimensioned assembly-coordinate drawing. "
                "Placement follows the etched stations and stated fit-up values."
            ),
            (
                "WT-006 contains four exact duplicate coincident CUT lines. "
                "They are removed only in the temporary import copy."
            ),
            (
                "Revision A remains a prototype subject to slot-coupon and "
                "complete physical dry-assembly verification."
            ),
        ],
    }
    METADATA_PATH.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    # Drop references before process exit. The separate validation command
    # starts a new OpenCascade session and reopens only the exported files.
    del assembly, placed, parts
    gc.collect()
    print(f"Built {len(PART_FILENAMES)} part STEP files and {assembly_step.name}")


def step_protocol(path: Path) -> str:
    header = path.read_text(encoding="latin-1", errors="ignore")[:20000]
    if "AUTOMOTIVE_DESIGN" in header:
        return "AP214"
    if "AP242" in header or "MANAGED_MODEL_BASED_3D_ENGINEERING" in header:
        return "AP242"
    if "CONFIG_CONTROL_DESIGN" in header:
        return "AP203"
    return "Unknown"


def contains_mesh_entities(path: Path) -> bool:
    content = path.read_text(encoding="latin-1", errors="ignore").upper()
    mesh_markers = (
        "FACETED_BREP",
        "TRIANGULATED_FACE",
        "TESSELLATED_FACE",
        "TESSELLATED_SOLID",
    )
    return any(marker in content for marker in mesh_markers)


def reopened_shape(path: Path) -> cq.Shape:
    imported = importers.importStep(str(path))
    values = imported.vals()
    if len(values) != 1:
        return cq.Compound.makeCompound(values)
    return values[0]


def validate_faces(shape: cq.Shape) -> bool:
    faces = shape.Faces()
    return bool(faces) and all(face.isValid() for face in faces)


def validate_part(path: Path) -> dict[str, Any]:
    shape = reopened_shape(path)
    solids = shape.Solids()
    box = shape.BoundingBox()
    valid = shape.isValid()
    faces_valid = validate_faces(shape)
    nonzero = bool(solids) and all(
        solid.Volume() > ZERO_VOLUME_MM3 for solid in solids
    )
    exact_thickness = math.isclose(
        box.zlen, THICKNESS_MM, abs_tol=DIMENSION_TOLERANCE_MM
    )
    protocol = step_protocol(path)
    no_mesh = not contains_mesh_entities(path)
    passed = (
        len(solids) == 1
        and valid
        and faces_valid
        and nonzero
        and exact_thickness
        and no_mesh
        and protocol in {"AP214", "AP242"}
    )
    result = {
        "filename": path.relative_to(ROOT).as_posix(),
        "sha256": sha256(path),
        "protocol": protocol,
        "solid_body_count": len(solids),
        "face_count": len(shape.Faces()),
        "bounding_mm": [box.xlen, box.ylen, box.zlen],
        "bounding_in": [
            box.xlen / INCH_TO_MM,
            box.ylen / INCH_TO_MM,
            box.zlen / INCH_TO_MM,
        ],
        "thickness_in": box.zlen / INCH_TO_MM,
        "volume_mm3": shape.Volume(),
        "imports_without_error": True,
        "topology_valid": valid,
        "all_faces_valid": faces_valid,
        "no_mesh_entities": no_mesh,
        "no_zero_volume_bodies": nonzero,
        "exactly_one_intended_solid": len(solids) == 1,
        "thickness_matches": exact_thickness,
        "reopen_result": "PASS" if passed else "FAIL",
    }
    del shape
    gc.collect()
    return result


def _volumes_match(
    actual: Iterable[float], expected: Iterable[float]
) -> bool:
    actual_sorted = sorted(actual)
    expected_sorted = sorted(expected)
    if len(actual_sorted) != len(expected_sorted):
        return False
    return all(
        math.isclose(
            left,
            right,
            rel_tol=VOLUME_REL_TOLERANCE,
            abs_tol=ZERO_VOLUME_MM3,
        )
        for left, right in zip(actual_sorted, expected_sorted)
    )


def step_product_names(path: Path) -> list[str]:
    """Read exported product names for a secondary hierarchy assertion."""

    content = path.read_text(encoding="latin-1", errors="ignore")
    return re.findall(r"PRODUCT\('([^']+)'", content)


def validate_assembly(
    path: Path, part_results: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    shape = reopened_shape(path)
    solids = shape.Solids()
    box = shape.BoundingBox()
    solid_volumes = [solid.Volume() for solid in solids]
    expected_volumes = [
        part_results[name]["volume_mm3"] for name in ASSEMBLY_COMPONENTS
    ]
    product_names = step_product_names(path)
    names_present = all(
        any(name in product_name for product_name in product_names)
        for name in ASSEMBLY_COMPONENTS
    )
    valid = shape.isValid()
    faces_valid = validate_faces(shape)
    nonzero = bool(solids) and all(
        volume > ZERO_VOLUME_MM3 for volume in solid_volumes
    )
    volumes_match = _volumes_match(solid_volumes, expected_volumes)
    protocol = step_protocol(path)
    no_mesh = not contains_mesh_entities(path)
    passed = (
        len(solids) == len(ASSEMBLY_COMPONENTS)
        and names_present
        and volumes_match
        and valid
        and faces_valid
        and nonzero
        and no_mesh
        and protocol in {"AP214", "AP242"}
    )
    result = {
        "filename": path.relative_to(ROOT).as_posix(),
        "sha256": sha256(path),
        "protocol": protocol,
        "solid_body_count": len(solids),
        "intended_component_count": len(ASSEMBLY_COMPONENTS),
        "intended_components": list(ASSEMBLY_COMPONENTS),
        "product_names": product_names,
        "all_intended_names_present": names_present,
        "component_volumes_match_individual_steps": volumes_match,
        "face_count": len(shape.Faces()),
        "bounding_mm": [box.xlen, box.ylen, box.zlen],
        "bounding_in": [
            box.xlen / INCH_TO_MM,
            box.ylen / INCH_TO_MM,
            box.zlen / INCH_TO_MM,
        ],
        "imports_without_error": True,
        "topology_valid": valid,
        "all_faces_valid": faces_valid,
        "no_mesh_entities": no_mesh,
        "no_zero_volume_bodies": nonzero,
        "reopen_result": "PASS" if passed else "FAIL",
    }
    del shape
    gc.collect()
    return result


def fmt_dimensions(values: list[float]) -> str:
    return " x ".join(f"{value:.6f}" for value in values)


def write_report(validation: dict[str, Any], solidworks_result: str) -> None:
    metadata = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    lines = [
        "# STEP Validation Report",
        "",
        "## Build configuration",
        "",
        f"- CAD software: {metadata['cad_software']}",
        f"- CAD kernel: {metadata['cad_kernel']}",
        f"- DXF reader: {metadata['dxf_reader']}",
        "- Authoritative geometry: `laser/dxf-parts/WT-001` through `WT-012`",
        f"- Export protocol: {validation['export_protocol']}",
        "- Model/export units: millimeters",
        f"- Material thickness: {THICKNESS_IN:.3f} in ({THICKNESS_MM:.3f} mm)",
        (
            "- Close/reopen method: build process exited; a separate validation "
            "process reopened every exported STEP with OpenCascade"
        ),
        "",
        "## Individual STEP results",
        "",
        (
            "| Generated filename | Solids | Bounding dimensions, in "
            "(X x Y x Z) | Thickness, in | Reopen | Topology/faces | Mesh |"
        ),
        "|---|---:|---:|---:|---|---|---|",
    ]
    for name in PART_FILENAMES:
        result = validation["parts"][name]
        topology = (
            "PASS"
            if result["topology_valid"] and result["all_faces_valid"]
            else "FAIL"
        )
        mesh = "None" if result["no_mesh_entities"] else "Detected"
        lines.append(
            "| `{filename}` | {solids} | {dimensions} | {thickness:.6f} | "
            "{reopen} | {topology} | {mesh} |".format(
                filename=result["filename"],
                solids=result["solid_body_count"],
                dimensions=fmt_dimensions(result["bounding_in"]),
                thickness=result["thickness_in"],
                reopen=result["reopen_result"],
                topology=topology,
                mesh=mesh,
            )
        )

    assembly = validation["assembly"]
    assembly_topology = (
        "PASS"
        if assembly["topology_valid"] and assembly["all_faces_valid"]
        else "FAIL"
    )
    lines.extend(
        [
            "",
            "## Assembly STEP result",
            "",
            f"- Generated filename: `{assembly['filename']}`",
            f"- Solid-body/component count: {assembly['solid_body_count']} / 10",
            (
                "- Intended components: "
                + ", ".join(f"`{name}`" for name in ASSEMBLY_COMPONENTS)
            ),
            (
                "- Bounding dimensions: "
                f"{fmt_dimensions(assembly['bounding_in'])} in (X x Y x Z)"
            ),
            f"- OpenCascade close/reopen result: {assembly['reopen_result']}",
            f"- Topology and all faces: {assembly_topology}",
            (
                "- Component-volume match to individual STEP files: "
                + (
                    "PASS"
                    if assembly["component_volumes_match_individual_steps"]
                    else "FAIL"
                )
            ),
            (
                "- Intended product names present: "
                + ("PASS" if assembly["all_intended_names_present"] else "FAIL")
            ),
            (
                "- Mesh bodies: "
                + ("none" if assembly["no_mesh_entities"] else "detected")
            ),
            (
                "- Zero-volume bodies: "
                + ("none" if assembly["no_zero_volume_bodies"] else "detected")
            ),
            "",
            "## Native CAD sources",
            "",
            "- Rebuild source: `cad/source/rebuild_weld_test.py`",
            "- Individual OpenCascade BREP files: `cad/native/parts/*.brep`",
            (
                "- Assembly OpenCascade XCAF/BREP files: "
                "`cad/native/assembly/*.xbf`, `cad/native/assembly/*.brep`"
            ),
            "- Build provenance: `cad/native/build-metadata.json`",
            "",
            "## SolidWorks verification",
            "",
            solidworks_result,
            "",
            "## Remaining warnings",
            "",
        ]
    )
    lines.extend(f"- {warning}" for warning in metadata["warnings"])
    lines.extend(
        [
            "",
            "## Overall result",
            "",
            (
                "**PASS** - all STEP files closed, reopened, and passed "
                "OpenCascade B-Rep validation."
                if validation["overall_open_cascade_result"] == "PASS"
                else "**FAIL** - one or more STEP files failed validation."
            ),
            "",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def validate(solidworks_result: str) -> None:
    if not METADATA_PATH.is_file():
        raise FileNotFoundError("Build metadata is missing; run the build command first")

    part_results: dict[str, dict[str, Any]] = {}
    for name in PART_FILENAMES:
        path = PART_STEP_DIR / f"{name}.step"
        if not path.is_file():
            raise FileNotFoundError(f"Generated STEP is missing: {path}")
        part_results[name] = validate_part(path)

    assembly_path = ASSEMBLY_STEP_DIR / f"{ASSEMBLY_FILENAME}.step"
    assembly_result = validate_assembly(assembly_path, part_results)
    all_pass = all(
        result["reopen_result"] == "PASS" for result in part_results.values()
    ) and assembly_result["reopen_result"] == "PASS"
    protocols = {
        result["protocol"] for result in part_results.values()
    } | {assembly_result["protocol"]}
    validation = {
        "cad_software": f"CadQuery {cq.__version__}",
        "cad_kernel": f"OpenCascade {OCP.__version__}",
        "export_protocol": ", ".join(sorted(protocols)),
        "parts": part_results,
        "assembly": assembly_result,
        "overall_open_cascade_result": "PASS" if all_pass else "FAIL",
        "solidworks_verification": solidworks_result,
    }
    VALIDATION_JSON_PATH.write_text(
        json.dumps(validation, indent=2) + "\n", encoding="utf-8"
    )
    write_report(validation, solidworks_result)
    if not all_pass:
        raise SystemExit("STEP close/reopen validation failed")
    print(
        f"Reopened and validated {len(PART_FILENAMES)} parts plus the "
        f"{len(ASSEMBLY_COMPONENTS)}-component assembly"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("build")
    validation = subparsers.add_parser("validate")
    validation.add_argument(
        "--solidworks-result",
        default=(
            "Pending - final SolidWorks application verification has not yet "
            "been run."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.command == "build":
        build()
    else:
        validate(args.solidworks_result)


if __name__ == "__main__":
    main()
